### PR TITLE
Fixed pipes crashing the server when having connections to every side

### LINKED ISSUE #5: Pipes having connections to all sides crash the server
Connecting something to every side of a container crashes the server with a NullReferenceException, however no trace of any mod files in the stacktrace.

### PR DESCRIPTION
**Pull request by IZEDx**
BlockPipe.SHAPES had no entry for when every connection is set.

Fixes #5

### CODE REVIEW

File: src/main/java/alexiil/mc/mod/pipes/blocks/BlockPipe.java [hunk 1]
```diff
@@ -62,8 +62,8 @@
             FACE_CENTER_SHAPES[dir.ordinal()] = VoxelShapes.union(faceShape, CENTER_SHAPE);
         }
 
-        SHAPES = new VoxelShape[2 * 2 * 2 * 2 * 2 * 2];
-        for (int c = 0; c < 0b111_111; c++) {
+        SHAPES = new VoxelShape[2 * 2 * 2 * 2 * 2 * 2 + 1];
+        for (int c = 0; c <= 0b111_111; c++) {
```
Comment (AlexIIL) [inline src/main/java/alexiil/mc/mod/pipes/blocks/BlockPipe.java:66]: I think it should really be `c <= 0b111_111` as the array is already big enough (as it's probably returning null from the last entry in the array, rather than throwing an index out of bounds exception).

Comment (IZEDx) [reply src/main/java/alexiil/mc/mod/pipes/blocks/BlockPipe.java:66]: Yeah I see, I was better safe than sorry while trying this out though. I could change this once I get home this evening.

Comment (AlexIIL) [reply src/main/java/alexiil/mc/mod/pipes/blocks/BlockPipe.java:66]: Ok! Other than that this looks good, thanks!
